name: sanjeevanai
description: AI-driven disease progression tracker for rural India
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1

  # HTTP & API
  dio: ^5.4.0

  # File Picker
  file_picker: ^10.1.9

  # Speech to Text (if needed later)
  speech_to_text: ^7.0.0

  # Local storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # Routing
  go_router: ^15.1.2

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # UI and themes
  flutter_svg: ^2.0.10
  google_fonts: ^6.2.0
  loading_indicator: ^3.1.0
  awesome_dialog: ^3.0.2

  # Charting for progress tracking
  fl_chart: ^1.0.0

  # Image manipulation (for previews or report thumbnails)
  image: ^4.2.0

  # Firebase (optional, add only if you're using Firebase backend)
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
